from pprint import pprint # devpkg for printing objects
import pandas as pd
import os
import yaml
from scripts import convert_external_genome
import warnings
import math

configfile: "config/config.yaml"

# Read the CSV file
CSV = config['input_manager']['path']
CSV_DATA = pd.read_csv(CSV, sep='\t')

# Path to species specific configuration files
SPECIES_PATH = config['input_manager']['config_species']

# Setup output folder
OUT_FOLDER = config['input_manager']['out_folder']

# Use the sample names as wildcards
SAMPLES = CSV_DATA['sample_name'].tolist()

# Create a dictionary for mapping sampleID to file paths
sample_to_illumina = {row['sample_name']: row['Illumina_read_files'].split(',') for idx, row in CSV_DATA.iterrows()}
sample_to_nanopore = {row['sample_name']: row['Nanopore_read_file'] for idx, row in CSV_DATA.iterrows()}
sample_to_assembly_file = {row['sample_name']: row['assembly_file'] for idx, row in CSV_DATA.iterrows()}

# ------------------ Species Mapping (from config) ------------------

# Load species_name_map from config file
species_name_map = config.get("species_map", {})

# Map each sample species (from sample sheet information) to the normalized species name used for the Species specific config
sample_to_organism = {
    row['sample_name']: species_name_map.get(row['organism'], row['organism'])
    for idx, row in CSV_DATA.iterrows()
}

# Debug check if species have not properly been mapped
unmapped_species = {
    row['organism'] for idx, row in CSV_DATA.iterrows()
    if row['organism'] not in species_name_map
}
if unmapped_species:
    warnings.warn("The following species are not mapped in config['species_map']: %s" % unmapped_species, UserWarning)

# ------------------ Load Species-Specific Configs ------------------

species_configs = {}
for species in set(sample_to_organism.values()):
    species_config_path = "%s%s.yaml" % (SPECIES_PATH, species)
    if os.path.exists(species_config_path):
        with open(species_config_path, "r") as species_config_file:
            species_configs[species] = yaml.load(species_config_file, 
                                                 Loader=yaml.Loader)
    else: # means the config is not found / available
        warnings.warn("Warning: Configuration file %s not found. Skipping analyses for %s." % (species_config_path, species), UserWarning)
        species_configs[species] = {}  # Empty config to ensure skipping analyses


database_path = config['input_manager']['database_path']

### Define rules where samtools is necessary



##############################################################################
#
#                              Snakefile 
#
##############################################################################

# Define the dynamic input for rule all
rule all:
    input:
        expand(
            "%s/{sample}/PlasmidFinder/" % OUT_FOLDER,
            sample = [
                s for s in SAMPLES
                if "plasmidfinder" in species_configs[sample_to_organism[s]]["analyses_to_run"]
            ]
        ),
        expand(
            "%s/{sample}/ResFinder/" % OUT_FOLDER,
            sample = [
                s for s in SAMPLES
                if "resfinder" in species_configs[sample_to_organism[s]]["analyses_to_run"]
            ]
        ),
        expand(
            "%s/{sample}/VirulenceFinder/" % OUT_FOLDER,
            sample = [
                s for s in SAMPLES
                if "virulencefinder" in species_configs[sample_to_organism[s]]["analyses_to_run"]
            ]
        ),
        expand(
            "%s/{sample}/SerotypeFinder/" % OUT_FOLDER,
            sample = [
                s for s in SAMPLES
                if "serotypefinder" in species_configs[sample_to_organism[s]]["analyses_to_run"]
            ]
        ),
        expand(
            "%s/{sample}/AMRFinder/{assembly}.tsv" % OUT_FOLDER,
            sample = [
                s for s in SAMPLES
                if "amrfinder" in species_configs[sample_to_organism[s]]["analyses_to_run"]
            ],
            assembly = ["spades", "skesa"]
        ),
        expand(
           "%s/{sample}/MLST/{assembler}_mlst.tsv" % OUT_FOLDER,
           sample = [
               s for s in SAMPLES 
               if "mlst" in species_configs[sample_to_organism[s]]["analyses_to_run"]
           ],
           assembler = ["spades", "skesa"]
        ),
        expand(
            "%s/{sample}/Variant_identifier/variants_{database}.tsv" %OUT_FOLDER,
            sample = [
                s for s in SAMPLES
                if "Variant_identifier" in species_configs[sample_to_organism[s]]["analyses_to_run"]
            ],
            database = "Cdiff_Toxins"
        ),
        expand(
            "%s/{sample}/CDiff_Repeat_identifier/{assembler}_repeat_types.tsv" %OUT_FOLDER,
            sample = [
                s for s in SAMPLES
                if "CDiff_Repeat_identifier" in species_configs[sample_to_organism[s]]["analyses_to_run"]
            ],
            assembler = ["spades", "skesa"]
        ),
        expand(
            "%s/{sample}/kmeraligner/{database}.res" % OUT_FOLDER,
            sample = [
                s for s in SAMPLES
                if "kmeraligner" in species_configs[sample_to_organism[s]]["analyses_to_run"]
            ],
            database = "ecoligenes"
        ),
        expand(
            "%s/{sample}/Kleborate/{assembler}" % OUT_FOLDER,
            sample=[
                s for s in SAMPLES
                if "kleborate" in species_configs[sample_to_organism[s]]["analyses_to_run"]
            ],
            assembler = ["spades", "skesa"]
        ),
        expand(
            "%s/{sample}/meningotype/{assembler}_meningotype.tsv" %OUT_FOLDER, 
            sample = [
                s for s in SAMPLES 
                if "meningotype" in species_configs[sample_to_organism[s]]["analyses_to_run"]
            ],
            assembler = "spades"
        ),
        expand(
            "%s/{sample}/CHtyper/{database}_chtyper.tsv" %OUT_FOLDER, 
            sample = [
                s for s in SAMPLES 
                if "CHtyper" in species_configs[sample_to_organism[s]]["analyses_to_run"]
            ],
            database = "fumCH_db"
        ),


include : "rules/assemblers.smk"
include : "rules/fetch_custom_dbs.smk"
include : "rules/setup_dbs.smk"
include : "rules/mappers.smk"
include : "rules/htslib_utils.smk"
include : "rules/finders.smk"
include : "rules/assemblers.smk"
include : "rules/characterizers.smk"
include : "rules/custom_wranglers.smk"
