amrfinder: "amrfinder_{assembler}.tsv"
plasmidfinder: "plasmidfinder.tsv"
resfinder: "resfinder.tsv"
pointfinder: "pointfinder.tsv"
disinfinder: "disinfinder.tsv"
serotypefinder: "serotypefinder.tsv"
virulencefinder: "virulencefinder.tsv"
lrefinder: "lrefinder_{database}.tsv"
kmeraligner: "custom_kmeralignment_{database}.tsv"
kma_filter: "kma_filter_{database}.tsv"
mlst: "mlst_{assembler}.tsv"
custom_blaster: "custom_blaster_{assembler}_{database}.tsv"
snp_identifier: "snp_identifier_{database}.tsv"
chtyper: "chtyper_{database}.tsv" 
deletion_identifier: "deletion_identifier_{assembler}_{database}.tsv"
cdiff_repeat_identifier: "cdiff_repeat_identifier_{assembler}.tsv"
meningotype: "meningotype_{assembler}.tsv"
kleborate: "kleborate_{assembler}.tsv"
sistr: "sistr_{assembler}.tsv"
seqsero2: "seqsero2.tsv"
spatyper: "spa_typing_{assembler}.tsv"