amrfinder: "{assemblers}.tsv"
plasmidfinder: "results_tab.tsv"
resfinder:
    - "ResFinder_results_tab.txt"
serotypefinder: "results_tab.tsv"
virulencefinder: "results_tab.tsv"
LREfinder: "{database}.tsv"
kmeraligner: "{database}.res"
kma_filter: "{database}.tsv"
mlst: "{assemblers}_mlst.tsv"
custom_blaster: "blast_{assemblers}_{database}.tsv"
snp_identifier: "{database}.tsv"
chtyper: "{database}_chtyper.tsv" 
deletion_identifier: "{assemblers}_{database}.tsv"
cdiff_repeat_identifier: "{assemblers}_repeat_types.tsv"
meningotype: "{assemblers}_meningotype.tsv"
kleborate:
    - "{assemblers}"
    - "{assemblers}"
sistr: "{assemblers}_sistr.tab"
seqsero2: "SeqSero_result.tsv"
spatyper: "{assemblers}_spatype_results.tsv"