# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ssi_analysis_utility',
                'doc_host': 'https://$GIT_USER_NAME.github.io',
                'git_url': 'https://github.com/$GIT_USER_NAME/ssi_analysis_utility',
                'lib_path': 'ssi_analysis_utility'},
  'syms': { 'ssi_analysis_utility.core': { 'ssi_analysis_utility.core.get_config': ('core.html#get_config', 'ssi_analysis_utility/core.py'),
                                           'ssi_analysis_utility.core.get_samplesheet': ( 'core.html#get_samplesheet',
                                                                                          'ssi_analysis_utility/core.py'),
                                           'ssi_analysis_utility.core.set_env_variables': ( 'core.html#set_env_variables',
                                                                                            'ssi_analysis_utility/core.py'),
                                           'ssi_analysis_utility.core.show_project_env_vars': ( 'core.html#show_project_env_vars',
                                                                                                'ssi_analysis_utility/core.py')},
            'ssi_analysis_utility.hello_world': { 'ssi_analysis_utility.hello_world.cli': ( 'hello_world.html#cli',
                                                                                            'ssi_analysis_utility/hello_world.py'),
                                                  'ssi_analysis_utility.hello_world.hello_world': ( 'hello_world.html#hello_world',
                                                                                                    'ssi_analysis_utility/hello_world.py')},
            'ssi_analysis_utility.some_string': {}}}
