kmeraligner_wrangler:
    options: --organism 'Escherichia coli'
    database: ecoligenes
    reads: True

snp_identifier:
    options: --organism 'Clostridioides difficile' --snp_region_buffer 5
    database: CdiffToxins

deletion_identifier:
    options: --organism 'Clostridioides difficile' --deletion_region_buffer 5 --overlap_fraction 0.5
    database: CdiffToxins
    assembler: shovill

minimap2:
    options: -ax asm5 --cs
    database: CdiffToxins
    assembler: shovill
    ignore: True

cdiff_repeat_identifier:
    repeats: TR6 TR10
    combos: TRST
    assembler: shovill

amrfinder:
    assembler: [shovill, skesa, spades]
    options: ""

samtools:
    view_options: -q 20
    sort_options: -n
    ignore: True


bcftools:
    view_options: -v indels -i 'INFO/DP>10'
    ignore: True

resfinder:
    options: --species 'ecoli'
    assembler: shovill
    reads: True

pointfinder:
    options: --species 'ecoli'
    assembler: shovill

disinfinder:
    options: --species 'ecoli'
    assembler: shovill

plasmidfinder: 
    options: ""
    assembler: shovill

virulencefinder:
    options: ""
    assembler: shovill

serotypefinder:
    assembler: shovill
    options: ""    

chtyper:
    database: fumCH
    reads: True

mlst:
    assembler: shovill  

blastn:
    options: "-perc_identity 90.0"
    assembler: shovill
    database : OXAndm

lrefinder:
    database : elmDB
    reads: True

kleborate:
    options: --preset escherichia
    assembler: shovill

meningotype:
    assembler: shovill

spatyper:
    assembler: shovill

seqsero2: 
    assembler: shovill

sistr:
    assembler: shovill

kmeraligner:
    database: [vancomycin, vancomycinOperon]
    reads: True
