kmeraligner_wrangler:
    options: --organism 'Escherichia coli'
    database: ecoligenes

snp_identifier:
    options: --organism 'Clostridioides difficile' --snp_region_buffer 5
    database: CdiffToxins

deletion_identifier:
    options: --organism 'Clostridioides difficile' --deletion_region_buffer 5 --overlap_fraction 0.5
    database: CdiffToxins
    assembler: shovill

minimap2:
    options: -ax asm5 --cs
    database: Cdiff_Toxins
    assembler: shovill

cdiff_repeat_identifier:
    repeats: TR6 TR10
    combos: TRST
    assembler: shovill

amrfinder:
    assembler: [shovill, skesa, spades]
    options: ""

samtools:
    view_options: -q 20
    sort_options: -n

bcftools:
    view_options: -v indels -i 'INFO/DP>10'

resfinder:
    options: --species 'Other'
    reads: True

pointfinder:
    options: --species 'Other'

disinfinder:
    options: --species 'Other'

plasmidfinder: 
    options: ""

virulencefinder:
    options: ""

serotypefinder:
    options: ""    

chtyper:
    database: fumCH 

mlst:
    assembler: shovill  

blastn:
    options: "-perc_identity 90.0"
    assembler: shovill
    database : OXAndm

lrefinder:
    database : elmDB

kleborate:
    options: --preset escherichia
    assembler: shovill

meningotype:
    assembler: shovill

spatyper:
  assembler: shovill

seqsero2: 
  assembler: shovill

sistr:
  assembler: shovill

kmeraligner:
    database : [vancomycin, vancomycinOperon]
