kmeraligner_wrangler:
    options: --organism 'Escherichia coli'
    database: ecoligenes
    reads: True

resfinder:
    options: --species 'Escherichia coli'
    reads: True

pointfinder:
    options: --species 'Escherichia coli'
    reads: True

disinfinder:
    options: --species 'Escherichia coli'
    reads: True

plasmidfinder: 
    reads: True

virulencefinder: 
    reads: True

serotypefinder: 
    reads: True

amrfinder:
    options: --organism 'Escherichia'
    assembler: shovill 

chtyper:
    database: fumCH 
    reads: True

mlst:
    assembler: shovill  

blastn:
    options: "-perc_identity 90.0"
    assembler: shovill
    database : OXAndm

kleborate:
    options: --preset escherichia
    assembler: shovill
