resfinder:
    options: --species 'Escherichia coli'
    assembler: shovill

pointfinder:
    options: --species 'Escherichia coli'
    assembler: shovill

plasmidfinder:
  options: "-l 80 -t 80"
  assembler: shovill

blastn:
  options: "-perc_identity 99.0"
  assembler: shovill
  database : OXAndm

virulencefinder: 
    assembler: shovill

serotypefinder:
    reads: True

kmeraligner_wrangler:
    options: --organism 'Escherichia coli'
    database: ecoligenes

chtyper:
    database: fumCH 
    reads: True

blastn:
    options: "-perc_identity 90.0"
    assembler: shovill
    database : OXAndm
