plasmidfinder:
    reads: True

virulencefinder:
    reads: True

serotypefinder:
    reads: True

resfinder:
    reads: False
    assembler: shovill
    options: --species 'Other'

amrfinder:
    options: --organism 'Enterococcus_faecium'
    assembler: [shovill]  

mlst:
    assembler: [shovill]  

lrefinder:
    database : [elmDB]
    reads: True

kmeraligner:
    database : [vancomycin, vancomycinOperon]
    reads: True
