plasmidfinder:
    reads: True

virulencefinder:
    reads: True

serotypefinder:
    reads: True

amrfinder:
    options: --organism 'Enterococcus_faecalis'
    assembler: [shovill]  

mlst:
    assembler: [shovill]  

lrefinder:
    database : [elmDB]
    reads: True

kmeraligner:
    database : [vancomycin, vancomycinOperon]
    reads: True
