plasmidfinder: true

virulencefinder: true

serotypefinder: true

amrfinder:
    options: --organism 'Enterococcus_faecalis'
    assembler: [shovill]  

mlst:
    assembler: [shovill]  

lrefinder:
    database : [elmDB]

kmeraligner:
    database : [vancomycin, vancomycinOperon]
