plasmidfinder: true

resfinder:
    options: --species 'Klebsiella'

virulencefinder: true

serotypefinder: true

amrfinder:
    options: --organism 'Klebsiella_pneumoniae'
    assemblers: shovill 

kleborate:
    options: --preset kpsc
    assemblers: shovill
    output: [klebsiella_pneumo_complex_hAMRonization_output.txt, klebsiella_pneumo_complex_output.txt]

mlst:
    assemblers: shovill  
