plasmidfinder: true

resfinder:
    options: --species 'Klebsiella'

virulencefinder: true

serotypefinder: true

amrfinder:
    options: --organism 'Klebsiella_pneumoniae'
    assemblers: shovill 

kleborate:
    options: --preset kpsc
    assemblers: shovill

mlst:
    assemblers: shovill  
