plasmidfinder:
  options: "-l 80 -t 80"
  assembler: shovill

blastn:
  options: "-perc_identity 99.0"
  assembler: shovill
  database : OXAndm

resfinder:
    options: --species 'Klebsiella'

pointfinder:
    options: --species 'Klebsiella'

disinfinder:
    options: --species 'Klebsiella'

virulencefinder: true

serotypefinder: true

amrfinder:
    options: --organism 'Klebsiella_pneumoniae'
    assembler: shovill 

kleborate:
    options: --preset kpsc
    assembler: shovill

mlst:
    assembler: shovill  
