resfinder:
  options: --species 'Salmonella enterica'

pointfinder:
  options: --species 'Salmonella enterica'

disinfinder:
  options: --species 'Salmonella enterica'


amrfinder:
  options: --organism 'Salmonella'
  assembler: shovill
  
mlst:
  assembler: shovill

seqsero2: true

sistr:
  assembler: shovill
