resfinder:
  options: --species 'Salmonella enterica'
  reads: True

pointfinder:
  options: --species 'Salmonella enterica'
  reads: True

disinfinder:
  options: --species 'Salmonella enterica'
  reads: True

amrfinder:
  options: --organism 'Salmonella'
  assembler: shovill
  
mlst:
  assembler: shovill

seqsero2: 
  reads: True

sistr:
  assembler: shovill
