kma_filter:
    options: --organism 'Escherichia coli'
    database: ecoligenes

# snp_identifier:
#     options: --organism 'Clostridioides difficile' --snp_region_buffer 5
#     database: Cdiff_Toxins

resfinder:
     options: --species 'ecoli'

pointfinder:
     options: --species 'ecoli'

# deletion_identifier:
#     options: --organism 'Clostridioides difficile' --deletion_region_buffer 5 --overlap_fraction 0.5
#     database: Cdiff_Toxins
#     assemblers: spades

assembly_minimap2:
    options: -ax asm5 --cs
    database: Cdiff_Toxins
    assemblers: spades

cdiff_repeat_identifier:
    repeats: TR6 TR10
    combos: TRST
    assemblers: spades

amrfinder:
    assemblers: [skesa, spades]
    options: ""

samtools:
    view_options: -q 20
    sort_options: -n

bcftools:
    view_options: -v indels -i 'INFO/DP>10'

disinfinder:
    options: --species 'ecoli'

plasmidfinder: 
    options: ""

virulencefinder:
    options: ""

serotypefinder:
    options: ""    

chtyper:
    database: fumCH_db 

mlst:
    assemblers: spades  

custom_blaster:
    options: "-perc_identity 90.0"
    assemblers: spades
    database : OXAndm

# meningotype:
#     assemblers: spades

spatyper:
  assemblers: spades

# seqsero2: true

sistr:
  assemblers: spades

kmeraligner:
    database : [vancomycin, vancomycin_operon]
