# When accessing this in the code you'll work with it as a dict.
# ENV variables will be replaced with their values. This is done with the envyaml package that is in the code template `load_config`.
# By convention all variables for the project should have the STREPTOFILE_* prefix.
# e.g
# name: ${STREPTOFILE_NAME}


input_parameters:
    sample_name: sample_name
    assembly_file: assembly_file
    Illumina_read_files: Illumina_read_files
    Nanopore_read_file: Nanopore_read_file


file_patterns: &input_file_patterns
    Illumina_read_file: (?P<sample_name>.+?)(?P<sample_number>(_S[0-9]+)?)(?P<lane>(_L[0-9]+)?)_(?P<paired_read_number>R[1|2])(?P<set_number>(_[0-9]+)?)(?P<file_extension>\.fastq\.gz)
    Nanopore_read_file: (?P<sample_name>.+?)_nanopore\.fastq\.gz
    assembly_fasta_file: (?P<sample_name>.+?)(\.fa|\.fna|\.fasta)
    metadata: r"(?P<metadata_name>.+?)(\.tsv|\.tab\.txt)"

input_manager:
    file_patterns: *input_file_patterns
    load_from_samplesheet: False
    load_from_folder: False
    input_folder: null
    output_folder: .
    assembly_file: null
    Illumina_read_files: null
    Nanopore_read_file: null
    samplesheet: null
    sample_name: null

analysis_settings:
    ### analysis_utility 
    blast_presence_absence: &blast_default_settings
        pident_threshold: 80
        cov_threshold: 80
        additional_blast_parameters: ""
        blast_header: qseqid sseqid pident length qlen qstart qend sstart send sseq evalue bitscore
        results_format: matrix
        files_to_clean:
            - blast

    assembly_lineage_determination: &assembly_lineage_determination_default_settings
        alias: lineage_determination
        percent_snp_threshold: 50
        files_to_clean:
            - delta
            - filtered_delta
            - frankenfasta

    ### Spyogenes_analysis

    Spyogenes:
        analyses_to_run: 
            emm_typing: Typing of M protein gene using blast against CDC curated alleles
            assembly_lineage_determination: Lineage determination based on presence of specified SNPs when mapping genome assembly against reference genome
            resistance_gene_detection: Presence of resistance gens tetM, ermA and ermB
            virulence_gene_detection: Presence of Streptococcal virulence genes from the Virulence Factor Database

        assembly_lineage_determination:
            <<: *assembly_lineage_determination_default_settings
            alias: assembly_lineage_determination
            reference_fasta_file: ${STREPTOFILE_RESOURCES_DIR}/lineage_determination/MGAS5005.fasta
            lineage_variant_file: ${STREPTOFILE_RESOURCES_DIR}/lineage_determination/Spyogenes_LOCs.tsv
        
        emm_typing:
            alias: emm_typing
            emm_allele_file: &local_emm_db_path ${STREPTOFILE_RESOURCES_DIR}/emm_typing/emm_alleles.fasta
            emm_cluster_file: ${STREPTOFILE_RESOURCES_DIR}/emm_typing/emm_enn_mrp_subgroups.txt
            blast_header: qseqid sseqid pident length qlen qstart qend sstart send sseq evalue bitscore
            files_to_clean:
                - blast
        
        resistance_gene_detection:
            alias: resistance_genes
            <<: *blast_default_settings
            query_fasta_file: ${STREPTOFILE_RESOURCES_DIR}/AMR/AMR_genes.fasta

        virulence_gene_detection:
            alias: virulence_genes
            <<: *blast_default_settings
            query_fasta_file: ${STREPTOFILE_RESOURCES_DIR}/virulence_factors/VFDB_genes.fasta
        
        Illumina_lineage_determination:
            alias: Illumina_lineage_determination
            reference_fasta_file: ${STREPTOFILE_RESOURCES_DIR}/lineage_determination/MGAS5005.fasta
            lineage_variant_file: ${STREPTOFILE_RESOURCES_DIR}/lineage_determination/Spyogenes_LOCs.tsv
            files_to_clean:
                - vcf
                - bam
                - bam_index
            
            
        
databases:
    emm_typing:
        local_path:  *local_emm_db_path
        online_path: https://ftp.cdc.gov/pub/infectious_diseases/biotech/tsemm/alltrimmed.tfa
        update_protocol: wget