####################### INPUT MANAGER #######################################
# This section defines the input manager settings, which specify the path 
# to the sample sheet and the output folder for analysis results.

sheet_path: examples/samplesheet.tsv  # Path to the input samplesheet (CSV/TSV file)
database_path: resources
out_path: examples/Results  # Folder where the analysis results will be saved