input_manager:
    samplesheet: examples/samplesheet.tsv  # Path to the input samplesheet (CSV/TSV file)
    database_path: resources
    config_species : workflow/configs_species
    metadata_path: examples/Metadata
    illumina_read_path: examples/Dataset/reads
    nanopore_read_path: examples/Dataset/reads
    assembly_path: examples/Dataset/assembly_path
    output_folder: examples/Results  # Folder where the analysis results will be saved
    temp_storage: examples/Dataset/databases
    result_catalogue: config/results_catalogue.yaml