####################### INPUT MANAGER #######################################
# This section defines the input manager settings, which specify the path 
# to the sample sheet and the output folder for analysis results.

input_manager:
    path: /dpssi/home/scrsim/ssi_analysis_utility/examples/samplesheet.tsv  # Path to the input samplesheet (CSV/TSV file)
    config_species : /dpssi/home/scrsim/ssi_analysis_utility/workflow/configs_species/
    out_folder: /dpssi/home/scrsim/ssi_analysis_utility/results  # Folder where the analysis results will be saved
    


###################### ANALYSIS & TOOLS SETTINGS ############################
# This section provides paths to the yaml file for the conda environemt,
# and script required for the various analysis

analysis_settings:
    
    kmeraligner:
        yaml : /dpssi/home/scrsim/ssi_analysis_utility/workflow/envs/kmeraligner.yaml

    resistance_gene_detection:
        yaml : /dpssi/home/scrsim/ssi_analysis_utility/workflow/envs/resistence_gene_detection.yaml

    emm_typing:
        yaml : /dpssi/home/scrsim/ssi_analysis_utility/workflow/envs/emm_typing.yaml

    assembly_lineage_determination:
        yaml : /dpssi/home/scrsim/ssi_analysis_utility/workflow/envs/assembly_lineage_determination.yaml
    
    plasmidfinder:
        yaml : /dpssi/home/scrsim/ssi_analysis_utility/workflow/envs/plasmidfinder.yaml
        
    resfinder:
        yaml : /dpssi/home/scrsim/ssi_analysis_utility/workflow/envs/resfinder.yaml

    virulencefinder:
        yaml : /dpssi/home/scrsim/ssi_analysis_utility/workflow/envs/virulencefinder.yaml
        
    LRE-finder:
        yaml : /dpssi/home/scrsim/ssi_analysis_utility/workflow/envs/LREfinder.yaml
        script: /dpssi/home/scrsim/ssi_analysis_utility/workflow/scripts  # Path to LRE-finder script directory
        
    serotypefinder:
        yaml : /dpssi/home/scrsim/ssi_analysis_utility/workflow/envs/serotypefinder.yaml

    kmerfinder:
        yaml : /dpssi/home/scrsim/ssi_analysis_utility/workflow/envs/kmerfinder.yaml

    cgMLSTFinder:
        yaml : /dpssi/home/scrsim/ssi_analysis_utility/workflow/envs/cgMLSTfinder.yaml
        script: /dpssi/home/scrsim/ssi_analysis_utility/workflow/scripts  # Path to cgMLSTFinder script directory

    kleborate:
        yaml : /dpssi/home/scrsim/ssi_analysis_utility/workflow/envs/kleborate.yaml
    
    chtyper:
        script: /dpssi/home/scrsim/ssi_analysis_utility/workflow/scripts  # Path to CHTyper script directory

    
    # Illumina lineage determination (commented out for now):
    # reference_fasta_file: /dpssi/home/scrsim/ssi_analysis_utility/resources/lineage_determination/MGAS5005.fasta  # Fasta file for reference genome
    # lineage_variant_file: /dpssi/home/scrsim/ssi_analysis_utility/resources/lineage_determination/Spyogenes_LOCs.tsv  # File with lineage variants



         




