analyses_to_run:
  spa_typing:
    assemblers: [shovill]

  mlst:
    assemblers: [shovill]  
    
  resfinder:
    options: ""

  plasmidfinder:
    options: ""

  virulencefinder:
    options: ""

  serotypefinder:
    options: ""
        
  amrfinder:
    assemblers: [shovill]
    options: ""
  
  meningotype:
    assemblers: [shovill]

  kmeraligner:
    database: [elmDB]
    options : -ID 80 -1t1 -cge

  LREfinder:
    database: [elmDB]