name: Label Validation

on:
  pull_request:
    types: [opened, edited, reopened, labeled, unlabeled, synchronize]

concurrency:
  group: pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  check-PR-label:

    runs-on: ubuntu-latest

    steps:
      - name: Validate labels
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const allowed = ["feature", "patch", "build"];

            const labels = pr.data.labels
              .map(l => l.name)
              .filter(l => allowed.includes(l));

            // deterministic rule
            if (labels.length !== 1) {
              core.setFailed(
                `PR must have exactly ONE version label (feature/patch/build). Found: ${labels.join(", ")}`
              );
              throw new Error("Invalid label state");
            }

  build:
    needs: check-PR-label

    strategy:
      matrix:
        os: [ubuntu-latest]
        #os: [ubuntu-22.04, ubuntu-latest, macos-latest] # Usable when we also have execution scripts available

    runs-on: ${{ matrix.os }}
    
    steps:
      # Check out the repository main folder
      - uses: actions/checkout@v4

      - name: Check ready + version state
        id: gate
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const labels = pr.data.labels.map(l => l.name);

            const hasReady = labels.includes("ready");
            const hasVersion = ["feature","patch","build"]
              .filter(l => labels.includes(l))
              .length === 1;

            return (hasReady && hasVersion) ? "true" : "false";

      - name: Stop if not ready
        if: steps.gate.outputs.result != 'true'
        run: |
          echo "Not ready or invalid state"
          exit 0


      - name: Setup Micromamba
        if: steps.gate.outputs.result != 'true'
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test-env
          init-shell: bash

      - name: Install dependencies
        if: steps.gate.outputs.result != 'true'
        shell: bash -l {0}
        run: |
          micromamba install conda --yes
          pip install .

      - name: Import test
        if: steps.gate.outputs.result != 'true'
        shell: bash -l {0}
        run: |
          python -c "import mmaseq; print(mmaseq.__version__)"
