name: Installation check

on:
  pull_request:
  workflow_dispatch:

jobs:
  install:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test-env
          init-shell: bash

      - name: Test conda installation
        shell: bash -l {0}
        run: |
          micromamba install conda --yes

          # install package from repo
          pip install .

      - name: Verify package imports
        shell: bash -l {0}
        run: |
          python -c "import mmaseq"
