name: Pull Requests label check

on:
  workflow_run:
    workflows: ["Pull Requests Automatic labelling"]
    types: [completed]

jobs:
  check-version-label:
    runs-on: ubuntu-latest

    steps:
      - name: Check labels
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            
            const labels = pr.data.labels
              .map(l => l.name)
              .filter(l =>
                ["feature","patch","build"].includes(l)
              );

            if (labels.length !== 1) {
              core.setFailed(
                `PR must contain exactly one version label (feature, patch, build). Found: ${labels.join(", ")}`
              );
            }
