name: Validate Pull Requests

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

concurrency:
  group: build-${{ github.event.pull_request.number || github.head_ref }}
  cancel-in-progress: true


jobs:
  check-label:
  
    if: ${{ github.event_name == 'pull_request' || github.event.issue.pull_request }}
    
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - name: Cool down for API sync
        run: sleep 20

      - name: Validate Single Version Label
        run: |
          # Dynamically determine PR number depending on what event triggered the run
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_NUM="${{ github.event.pull_request.number }}"
          else
            PR_NUM="${{ github.event.issue.number }}"
          fi
          
          REPO="${{ github.repository }}"
          echo "Checking labels for PR #$PR_NUM in $REPO..."
          
          # Fetch current labels
          CURRENT_LABELS=$(gh pr view "$PR_NUM" -R "$REPO" --json labels --jq '.labels[].name')
          
          MATCH_COUNT=0
          FOUND_LABELS=()
          
          for label in $CURRENT_LABELS; do
            if [[ "$label" == "major" || "$label" == "minor" || "$label" == "patch"  || "$label" == "build" ]]; then
              MATCH_COUNT=$((MATCH_COUNT + 1))
              FOUND_LABELS+=("$label")
            fi
          done
          
          echo "Found version labels: ${FOUND_LABELS[*]}"
          echo "Total count: $MATCH_COUNT"
          
          if [ "$MATCH_COUNT" -eq 1 ]; then
            echo "Success: Exactly one versioning label is applied (${FOUND_LABELS})."
            exit 0
          elif [ "$MATCH_COUNT" -eq 0 ]; then
            echo "Error: Pull Request is missing a version label (major, minor, patch, or build)."
            exit 1
          else
            echo "Error: Pull Request has multiple version labels (${FOUND_LABELS[*]}). Only one is allowed."
            exit 1
          fi

  build:
    if: "!contains(github.event.pull_request.labels.*.name, 'build')"
    needs: check-label

    strategy:
      matrix:
        os:
          - ubuntu-latest 
          - ubuntu-22.04 
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checking PR status
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name);

            if (labels.includes('build')) {
              console.log("PR is labelled 'build', thus no changes in software is imminent. Check is done sucessfully!");
            }


      - name: Setup Micromamba
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'build') }}
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test-env
          init-shell: bash

      - name: Test conda installation
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'build') }}
        shell: bash -l {0}
        run: |
          micromamba install conda --yes
          conda config --set channel_priority strict

          # install package from repo
          pip install .

      - name: Verify package imports
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'build') }}
        shell: bash -l {0}
        run: |
          mmaseq --version

      - name: Test pipeline
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'build') }}
        shell: bash -l {0}
        run: |
          mmadeploy --deploy_dir ~/test --threads 3 --test --verbosity 2
