name: Bump version

on: 
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  bump_version:
    if: |
      github.event.pull_request.merged == true && 
      !contains(github.event.pull_request.labels.*.name, 'build')

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          token: ${{ secrets.VERSION }}

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Get label
        id: label
        run: |
          echo "LABEL=${{
            contains(github.event.pull_request.labels.*.name, 'major') && 'major' ||
            contains(github.event.pull_request.labels.*.name, 'feature') && 'feature' ||
            contains(github.event.pull_request.labels.*.name, 'patch') && 'patch'
          }}" >> $GITHUB_OUTPUT

      - name: Bump version
        id: bumper
        run: |
          python .github/scripts/bump_version.py \
            "${{ steps.label.outputs.LABEL }}"

      - name: Commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
          git add src/mmaseq/__version__.py
          
          # Only commit if there are staged changes
          if ! git diff-index --quiet --cached HEAD --; then
            NEW_VER="${{ steps.bumper.outputs.new_version }}"
            git commit -m "Bump version to v$NEW_VER"
            git push
          else
            echo "No changes detected, skipping commit"
          fi
